### ISSUE TITLE
华为手机在使用过程中会报错

### ISSUE THREAD

**Issue by SamKing1992** [zhuguohui/WXSoundRecord#1]
java.lang.IllegalStateException: The specified message queue synchronization  barrier token has not been posted or has already been removed.
        at android.os.MessageQueue.removeSyncBarrier(MessageQueue.java:587)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2148)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8872)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1280)
        at android.view.Choreographer.doCallbacks(Choreographer.java:1019)
        at android.view.Choreographer.doFrame(Choreographer.java:911)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1248)
        at android.os.Handler.handleCallback(Handler.java:900)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8668)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

报错如上,查了下相关问题尝试过使用new Message() 或者Message.obtain等方法都没有解决
机型:华为mate 40 pro
麻烦看下 感谢!

**Comment by wzJun1** [comment]
+1

**Comment by wengo123** [comment]
示例中在子线程中不断刷新UI 用了invalidate()，应该采用postInvalidate()刷新，虽然invalidate()并不能立即重绘视图。invalidate()会将重绘的请求发送给UI线程，然后等待UI线程完成绘制，频繁不断的调用invalidate()，导致请求堆积，UI线程无法及时处理.不断的操作，最终导致整个UI线程卡死，有大量的Message消息无法处理
